"""followers

Revision ID: 029b3ce77719
Revises: bd546faf8f35
Create Date: 2022-11-27 18:39:27.159550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '029b3ce77719'
down_revision = 'bd546faf8f35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
